name: Build and Deploy

on:
  push:
    # branches:
    #   - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' 

      - name: Install Dependencies
        run: |
          npm ci
          npm install atomic-algolia --save

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.113.0'
          
      - name: Build
        run: hugo

      - name: Run Algolia
        run: |
          echo "ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}"
          echo "ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}"
          echo "ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}"
          echo "ALGOLIA_INDEX_FILE: ${{ secrets.ALGOLIA_INDEX_FILE }}"
          
          ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }} \
          ALGOLIA_ADMIN_KEY=${{ secrets.ALGOLIA_ADMIN_KEY }} \
          ALGOLIA_INDEX_NAME=${{ secrets.ALGOLIA_INDEX_NAME }} \
          ALGOLIA_INDEX_FILE=${{ secrets.ALGOLIA_INDEX_FILE }} \
          npm run algolia


